# Generated by Django 3.2.5 on 2022-02-15 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='price_in_rupees',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='weight',
            new_name='weight_in_kgs',
        ),
    ]
